#! /usr/bin/env python
from __future__ import division

import rospy
from math import pi, asin, acos
from tf.transformations import euler_from_quaternion
from geometry_msgs.msg import Twist, PoseStamped
from nav_msgs.msg import Odometry
from std_msgs.msg import Float32, Bool

from diff_drive import goal_controller
from diff_drive import pose

class GoToGoalNode:

    def __init__(self):
        self.controller = goal_controller.GoalController()

    def main(self):
        rospy.init_node('diff_drive_go_to_goal')
        self.distPub = rospy.Publisher('~distance_to_goal',
                                       Float32, queue_size=10)
        self.twistPub = rospy.Publisher('cmd_vel',
                                        Twist, queue_size=10)

        self.nodeName = rospy.get_name()
        rospy.loginfo("{0} started".format(self.nodeName))

        rospy.Subscriber('odom', Odometry, self.odomCallback)
        rospy.Subscriber('move_base_simple/goal', PoseStamped, self.goalCallback)

        self.goal_achieved_pub = rospy.Publisher('goal_achieved', Bool,
                                                 queue_size=1)

        self.rate = rospy.get_param('~rate', 10.0)
        self.dT = 1 / self.rate
        self.kP = rospy.get_param('~kP', 3.0)
        self.kA = rospy.get_param('~kA', 8.0)
        self.kB = rospy.get_param('~kB', -1.5)
        self.linearTolerance = rospy.get_param('~linear_tolerance', 0.05)
        self.angularTolerance = rospy.get_param('~angular_tolerance',
                                                3/180*pi)
        self.maxLinearSpeed = rospy.get_param('~max_linear_speed', 0.1)
        self.maxAngularSpeed = rospy.get_param('~max_angular_speed', 0.3)

        self.controller.setConstants(self.kP, self.kA, self.kB)
        self.controller.setLinearTolerance(self.linearTolerance)
        self.controller.setAngularTolerance(self.angularTolerance)
        self.controller.setMaxLinearSpeed(self.maxLinearSpeed)
        self.controller.setMaxAngularSpeed(self.maxAngularSpeed)

        # Set whether to allow movement backward. Backward movement is
        # safe if the robot can avoid obstacles while traveling in
        # reverse. We default to forward movement only since many
        # sensors are front-facing.
        self.controller.setForwardMovementOnly(
            rospy.get_param('~forwardMovementOnly', True))

        self.initPose()
        self.goal = None
        
        rate = rospy.Rate(self.rate)
        self.lastTwistTime = rospy.get_time()
        while not rospy.is_shutdown():
            if self.goal is not None:
                self.publish()
            rate.sleep()

    def initPose(self):
        self.pose = pose.Pose()
        self.pose.x = 0
        self.pose.y = 0
        self.pose.theta = 0

    def publish(self):
        if self.controller.atGoal(self.pose, self.goal):
            desired = pose.Pose()
        else:
            desired = self.controller.getVelocity(self.pose, self.goal,
                                                  self.dT)

        # if self.goal is not None \
        #    and (desired.xVel!=0.0 or desired.thetaVel!=0.0):
        #     rospy.loginfo(
        #         'current=(%f,%f,%f) goal=(%f,%f,%f)  xVel=%f thetaVel=%f',
        #         self.pose.x, self.pose.y, self.pose.theta,
        #         self.goal.x, self.goal.y, self.goal.theta,
        #         desired.xVel, desired.thetaVel)

        d = self.controller.getGoalDistance(self.pose, self.goal)
        self.distPub.publish(d)

        twist = Twist()
        twist.linear.x = desired.xVel
        twist.angular.z = desired.thetaVel
        self.twistPub.publish(twist)

        # Forget the goal if achieved.
        if self.controller.atGoal(self.pose, self.goal):
            rospy.loginfo('Goal achieved')
            self.goal = None
            msg = Bool()
            msg.data = True
            self.goal_achieved_pub.publish(msg)

    def odomCallback(self, newPose):
        self.pose = self.get_angle_pose(newPose.pose.pose)

    def goalCallback(self, goal):
        self.goal = self.get_angle_pose(goal.pose)
        rospy.loginfo('Goal: (%f,%f,%f)', self.goal.x, self.goal.y,
                      self.goal.theta)

    def get_angle_pose(self, quaternion_pose):
        q = [quaternion_pose.orientation.x,
             quaternion_pose.orientation.y,
             quaternion_pose.orientation.z,
             quaternion_pose.orientation.w]
        roll, pitch, yaw = euler_from_quaternion(q)

        angle_pose = pose.Pose()
        angle_pose.x = quaternion_pose.position.x
        angle_pose.y = quaternion_pose.position.y
        angle_pose.theta = yaw
        return angle_pose

if __name__ == '__main__':
    try:
        node = GoToGoalNode()
        node.main()
    except rospy.ROSInterruptException:
        pass
